# GENERAL CONFIGURATION
CLIENT_PROTO = b'MNPC01'  #: Client protocol identifier
WORKER_PROTO = b'MNPW01'  #: Worker protocol identifier

HB_INTERVAL = 3000  #: Heartbeat interval in milliseconds
HB_RETRIES = 9      #: Heartbeat retries before quiting

DEFAULT_INTEFACE = 'wboard'  #: The interface used by the underlying network

# MSG TYPES
MSG_READY = b'\x01'
MSG_QUERY = b'\x02'
MSG_REPLY = b'\x03'
MSG_HEARTBEAT = b'\x04'
MSG_DISCONNECT = b'\x05'

# BROKER COMMANDS
MSG_WINFO = b'br01'

# HW SCANNER COMMANDS
MSG_ECHO = b'hs01'
MSG_CPUPERCENT = b'hs02'
MSG_CPUTIMES = b'hs03'
MSG_CPUTIMESPERCENT = b'hs04'
MSG_CPUCOUNT = b'hs05'
MSG_CPUSTATS = b'hs06'
MSG_NETIOCOUNTERS = b'hs07'
MSG_NETCONNECTIONS = b'hs08'
MSG_NETIFADDRS = b'hs09'
MSG_NETIFSTATS = b'hs10'
MSG_BOOTTIME = b'hs11'
MSG_MEMORYINFO = b'hs12'
MSG_MEMORYPERCENT = b'hs13'
MSG_CONNECTIONS = b'hs14'
MSG_DUMP = b'hs15'

# TG COMMANDS
MSG_SENDTRAFFIC = b'tg01'
MSG_STOPSENDINGTRAFFIC = b'tg02'
MSG_MEASUREBANDWIDTH = b'tg03'

# BABEL SCANNER COMMANDS
MSG_FLUSH = b'pb01'
MSG_DUMP_B = b'pb02'
MSG_MONITOR = b'pb03'
MSG_UNMONITOR = b'pb04'

# WORKER TYPES
WK_TYPE_BROKER = b'00'
WK_TYPE_PC = b'01'
WK_TYPE_UMV = b'02'
WK_TYPE_UAV = b'03'
WK_TYPE_FOREIGN = b'04'

# WORKER STATUS
WORKER_OFFLINE_STATUS = b'lost'
WORKER_ONLINE_STATUS = b'online'
WORKER_BUSY_STATUS = b'busy'
WORKER_INACTIVE_STATUS = b'inactive'
WORKER_FOREIGN_STATUS = b'foreign'

# ROUTING PROTOCOLS
ROUTING_BABEL = b'rp01'
ROUTING_BATMAN = b'rp02'

# SERVICES
SERVICE_ECHO = b'echo'
SERVICE_BROKER = b'broker'
